version: '3.8'
services:
  frontend:
    image: nicolfo/thesis-management-frontend:sprint2
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: always

  backend:
    image: 'nicolfo/thesis-management:sprint2.1'
    ports:
      - "8081:8081"
    expose:
      - "8081"
    build:
      context: src/main/java
    depends_on:
      - db
      - keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - KEYCLOAK_HOST=keycloak

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password


  keycloak:
    image: 'quay.io/keycloak/keycloak:22.0.5'
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    configs:
      - source: keycloak-config
        target: /opt/keycloak/data/import/oidcrealm-realm.json
    command: start-dev --import-realm

configs:
  keycloak-config:
    file: ./oidcrealm-realm.json